const attributesSWApi = {
  people: [
    { title: 'Name:', property: 'name' },
    { title: 'Species:', property: 'species' },
    { title: 'Height:', property: 'height' },
    { title: 'Mass:', property: 'mass' },
    { title: 'Hair Color:', property: 'hair_color' },
    { title: 'Skin Color:', property: 'skin_color' },
    { title: 'Eye Color:', property: 'eye_color' },
    { title: 'Birth Year:', property: 'birth_year' },
    { title: 'Gender:', property: 'gender' },
    { title: 'Homeworld:', property: 'homeworld' },
  ],
  species: [
    { title: 'Name:', property: 'name' },
    { title: 'Classification:', property: 'classification' },
    { title: 'Designation:', property: 'designation' },
    { title: 'Language:', property: 'language' },
    { title: 'Avg Lifespan:', property: 'average_lifespan' },
    { title: 'Avg Height:', property: 'average_height' },
    { title: 'Hair Colors:', property: 'hair_colors' },
    { title: 'Skin Colors:', property: 'skin_colors' },
    { title: 'Eye Colors:', property: 'eye_colors' },
  ],
  films: [
    { title: 'Title:', property: 'title' },
    { title: 'Data Created:', property: 'data_created' },
    { title: 'Director:', property: 'director' },
    { title: 'Opening Crawl:', property: 'opening_crawl' },
  ],
  starships: [
    { title: 'Model:', property: 'model' },
    { title: 'Starship Class:', property: 'starship_class' },
    { title: 'Manufacturer:', property: 'manufacturer' },
    { title: 'Cost:', property: 'cost_in_credits' },
    { title: 'Speed:', property: 'max_atmosphering_speed' },
    { title: 'Hyperdrive Rating:', property: 'hyperdrive_rating' },
    { title: 'MGLT:', property: 'MGLT' },
    { title: 'Length:', property: 'length' },
    { title: 'Cargo Capacity:', property: 'cargo_capacity' },
    { title: 'Mimimum Crew:', property: 'crew' },
    { title: 'Passengers:', property: 'passengers' },
  ],
  planets: [
    { title: 'Name:', property: 'name' },
    { title: 'Diameter:', property: 'diameter' },
    { title: 'Rotation Period:', property: 'rotation_period' },
    { title: 'Orbital Period:', property: 'orbital_period' },
    { title: 'Gravity:', property: 'gravity' },
    { title: 'Population:', property: 'population' },
    { title: 'Climate:', property: 'climate' },
    { title: 'Terrain:', property: 'terrain' },
    { title: 'Surface Water:', property: 'surface_water' },
  ],
  vehicles: [
    { title: 'Model:', property: 'model' },
    { title: 'Manufacturer:', property: 'manufacturer' },
    { title: 'Class:', property: 'vehicle_class' },
    { title: 'Cost:', property: 'cost_in_credits' },
    { title: 'Speed:', property: 'max_atmosphering_speed' },
    { title: 'Length:', property: 'length' },
    { title: 'Cargo Capacity:', property: 'cargo_capacity' },
    { title: 'Minimum Crew:', property: 'crew' },
    { title: 'Passengers:', property: 'passengers' },
  ],
}

export default attributesSWApi
